apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: backstage-ulp
    environment: dev
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-portal
  source:
    repoURL: https://github.com/pdaxh/backstage-ulp.git
    path: k8s/overlays/dev
    targetRevision: main
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
