apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - backstage-production.yaml

images:
  - name: ghcr.io/pdaxh/backstage-ulp
    newTag: latest

replicas:
  - name: backstage
    count: 3
